/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nicolekeane (https://sketchfab.com/nicolekeane)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/matilda-7ddedfb652bd4ea091bc3de27f98fc02
Title: Matilda
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Girl = React.memo(function Girl(props) {
  const { nodes, materials } = useGLTF("/models/matilda.glb");

  const modelRef = useRef();
  useFrame((state) => {
    modelRef.current.position.y =
      -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;
  });

  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      position={[0, -1.5, 0]}
      scale={[0.02, 0.02, 0.02]}
      rotation={[0.25, 0, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface1_surfaceShader1_0.geometry}
        material={materials.surfaceShader1}
      />
    </group>
  );
});

export default Girl;
useGLTF.preload("/models/matilda.glb");
